# Generated by Django 3.2.5 on 2021-07-13 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miTaller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('nombreReparacion', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('codigoReparacion', models.IntegerField()),
                ('descripcionReparacion', models.TextField()),
                ('categoriaRep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miTaller.categoriareparacion')),
            ],
        ),
    ]
