# Generated by Django 3.2.5 on 2021-07-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miTaller', '0002_reparacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='imagen',
            field=models.ImageField(null=True, upload_to='taller'),
        ),
    ]
