# Generated by Django 3.2.5 on 2021-07-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miTaller', '0004_contacto'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparacion',
            name='publicarReparacion',
            field=models.BooleanField(default=False),
        ),
    ]
